# SDK 最低支持版本为 iOS 8.0
platform:ios, '8.0'

# github 官方 pod 源
source 'https://github.com/CocoaPods/Specs.git'
# 阿里云 pod 源
source 'https://github.com/aliyun/aliyun-specs.git'

target “RCTAliLiving” do
    use_frameworks!
    pod 'AlicloudALBBOpenAccount', '3.4.0.30'
    pod 'IMSApiClient', '1.2.0'
    pod 'IMSAuthentication', '1.1.0'
    pod 'MJRefresh', '3.1.15'
    pod 'ZipArchive', '1.4.0'
    pod 'IMSDeviceCenter', '1.5.0'
    pod 'CocoaAsyncSocket', '7.4.2'
    pod 'Reachability', '3.2'
    pod 'IMSThingCapability', '1.5.0'
    pod 'AlicloudPushIoT', '1.9.5.3'
    pod 'IMSMobileChannel', '1.5.0'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['RxSwift'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
            else
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
        end
    end
end